# Generated by Django 3.2.3 on 2021-06-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images2',
            field=models.ImageField(blank=True, upload_to='productimages/'),
        ),
        migrations.AddField(
            model_name='product',
            name='images3',
            field=models.ImageField(blank=True, upload_to='productimages/'),
        ),
        migrations.AddField(
            model_name='product',
            name='images4',
            field=models.ImageField(blank=True, upload_to='productimages/'),
        ),
    ]
