# Generated by Django 3.2.3 on 2021-07-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
