# Generated by Django 3.2.3 on 2021-07-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20)),
                ('coupon_rate', models.FloatField()),
                ('coupon_start', models.DateField()),
                ('coupon_end', models.DateField()),
            ],
        ),
    ]
