# Generated by Django 3.2.3 on 2021-07-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureadmin', '0003_usedoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedoffer',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
