# Generated by Django 3.2.3 on 2021-07-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_offer',
            field=models.FloatField(null=True),
        ),
    ]
